name = "extractor"
main = "src/index.js"
compatibility_date = "2022-07-21"

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
  binding = "kv_symbols"
  id = "9294e00ff81a4d29bd601db2ae6a213b"

[[kv_namespaces]]
  binding = "kv_names"
  id = "f358a14d2cc24fcc9dd9a35b263934aa"

[[kv_namespaces]]
  binding = "kv_quotes"
  id = "cd682c22dcc04f0f8cab872c1eec8c74"