name = "trader.extract"
main = "src/index.js"
compatibility_date = "2022-07-21"

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
  binding = "kv_indexes"
  id = ""

[[kv_namespaces]]
  binding = "kv_symbols"
  id = ""

[[kv_namespaces]]
  binding = "kv_names"
  id = ""

[[kv_namespaces]]
  binding = "kv_quotes"
  id = ""