name = "authenticator"
main = "src/index.js"
compatibility_date = "2022-07-21"

[[kv_namespaces]]
  binding = "kv_hashes"
  id = "64e5143a442f4be0b07d130f1e320251"

[[kv_namespaces]]
  binding = "kv_salts"
  id = "893b9eda26e54f90ba449485df91e716"