name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3
      - name: Actions Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Node Install
        run: npm ci
      - name: Angular Build
        run: npm run build -- --configuration production
      - name: Upload Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: artifacture
          path: frontend/dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: artifacture
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit Git
        run: |
          ls
          git switch -c built
          git add trader/*
          git commit -am "Deploy"
          git push origin built
